# Generated by Django 4.0 on 2022-03-25 00:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('preparadoParaMostrar', models.BooleanField(default=False, verbose_name='¿La publicación esta lista para ser mostrada? ')),
                ('calificacionCliente', models.CharField(choices=[('1', '1 estrella  (mala)'), ('2', '2 estrellas (insatisfecho)'), ('3', '3 estrellas (regular)'), ('4', '4 estrellas (bueno)'), ('5', '5 estrellas (excelente)')], default='0', max_length=1, verbose_name='Satisfaccion del cliente')),
                ('likes', models.IntegerField(default=0, verbose_name='Likes recibidos')),
                ('visitas', models.IntegerField(default=0, verbose_name='visitas recibidas')),
                ('titulo', models.CharField(max_length=150, verbose_name='Titulo')),
                ('imagen', models.ImageField(upload_to='imagenes_de_proyectos', verbose_name='Imagen del proyecto')),
                ('prioridad', models.PositiveSmallIntegerField(default=0, verbose_name='Prioridad de aparicion')),
                ('descripccion', models.TextField(default='', null=True, verbose_name='Breve descripccion del proyecto:')),
                ('contenido', models.TextField(default='', verbose_name='Descripccion mas extensa de lo que que trata el proyecto')),
                ('categorias', models.ManyToManyField(related_name='get_proyectos', to='portafolio.Categoria')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['prioridad'],
            },
        ),
        migrations.CreateModel(
            name='Apartado_Portafolio',
            fields=[
                ('apartado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='about.apartado')),
                ('frasePortafolio', models.CharField(max_length=200, null=True, verbose_name='Frase de presentación del portafolio')),
                ('proyectosDestacados', models.ManyToManyField(to='portafolio.Proyecto')),
            ],
            options={
                'verbose_name': 'Presentacion de la pagina principal del: Portafolio de proyectos',
                'verbose_name_plural': 'Presentacion de la pagina principal del: Portafolio de proyectos',
            },
            bases=('about.apartado',),
        ),
    ]
