# Generated by Django 4.0 on 2022-03-25 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartado_Contacto',
            fields=[
                ('apartado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='about.apartado')),
            ],
            options={
                'verbose_name': 'Presentacion de la pagina de: contacto',
            },
            bases=('about.apartado',),
        ),
        migrations.CreateModel(
            name='MensajeRecibido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=300, verbose_name='Asunto del mensaje')),
                ('mensaje', models.TextField(verbose_name='Cuerpo del mensaje')),
            ],
            options={
                'verbose_name': 'Mensaje de confirmacion de recibido',
                'verbose_name_plural': 'Mensaje de confirmacion de recibido',
            },
        ),
        migrations.CreateModel(
            name='RedCotacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRedContacto', models.CharField(choices=[('1', 'Facebook'), ('2', 'Youtube'), ('3', 'Instragram'), ('4', 'LinkedIn'), ('5', 'Twitter'), ('6', 'Github')], max_length=1, unique=True, verbose_name='Red social')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Enlace')),
            ],
            options={
                'verbose_name': 'Red de contacto',
                'verbose_name_plural': 'Redes de contacto',
                'ordering': ['nombreRedContacto'],
            },
        ),
    ]
