# Generated by Django 4.0 on 2022-03-25 00:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('preparadoParaMostrar', models.BooleanField(default=False, verbose_name='¿La publicación esta lista para ser mostrada? ')),
                ('nombre', models.CharField(max_length=150, null=True, verbose_name='Nombre del diseño de portada:')),
                ('imagenPortada', models.ImageField(upload_to='fotosApartados', verbose_name='Imagen del apartado de portada:')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DatosEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre:')),
                ('sector', models.CharField(max_length=150, verbose_name='Sector:')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha de creacion:')),
                ('correoElectronico', models.EmailField(default=None, max_length=254, null=True, verbose_name='Correo electronico: ')),
                ('numeroTelefonico', models.CharField(default=None, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Datos de la empresa',
                'verbose_name_plural': 'Datos de la empresa',
            },
        ),
        migrations.CreateModel(
            name='Apartado_About',
            fields=[
                ('apartado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='about.apartado')),
                ('foto', models.ImageField(upload_to='fotosEmpresa', verbose_name='Foto de la empresa:')),
                ('descripccion', models.TextField(default='', verbose_name='Descripccion de empresa:')),
            ],
            options={
                'verbose_name': 'Presentacion de la pagina de: about',
                'verbose_name_plural': 'Presentacion de la pagina de: about',
            },
            bases=('about.apartado',),
        ),
    ]
