# Generated by Django 4.0 on 2022-03-25 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartado_Dashboard',
            fields=[
                ('apartado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='about.apartado')),
            ],
            options={
                'verbose_name': 'Presentacion de la pagina de: dashboard',
            },
            bases=('about.apartado',),
        ),
    ]
